### PR TITLE
fix(shutdown): correctly handle rocket errors

### LINKED ISSUE #120: Process never exits when fails to bind the port in v0.1.5 [Server]
**Describe the bug**
Binary v0.1.5 does not exit when it fails to bind the port. This is making the process to hang when started. 

**To Reproduce**
- Run a process in port 9090
- Run the binary with -p 9090
- We will get an error in the terminal but the process never exits

**Expected behavior**
The process should exit with a particular code. Before it was `101`.

**Screenshots**
Here you can see that 0.1.5 hangs.

image

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.6

### PR DESCRIPTION
**Pull request by robertohuertasm**
## What problem are you trying to solve?
Fixes #120 

## What is your solution?
If we're not using the `keep alive` functionality, we will just wait for the Rocket thread to finish.

If not, we will await for the first occurrence. Either the Rocket thread finishes (for instance, due to a panic...) or the keep alive functionality notifies the shutdown and causes the `shutdown handle` to finish.

## Other considerations
I took the time to fix some clippy issues. It was impossible to even commit without doing `--no-verify`. I'm afraid potential contributors may be facing the same issue.  Is that expected or are you not getting that at all when trying to commit to the repo?

IDE-1744

### CODE REVIEW

**Review by juli1 — APPROVED** [review]
Thanks for your contribution! I never had any issue with clippy in the past. It should be working normally.

**Comment by robertohuertasm** [comment]
Thanks @juli1! Not sure if you were planning to create a release soon, but I'd really appreciate having this already internally in order to leverage this behavior in VS Code.

**Comment by juli1** [comment]
> Thanks @juli1! Not sure if you were planning to create a release soon, but I'd really appreciate having this already internally in order to leverage this behavior in VS Code.

New release should come tomorrow once [this](https://github.com/DataDog/datadog-static-analyzer/pull/119) is merged.

**Comment by robertohuertasm** [comment]
Saw v0.1.6 already! Thank you for that! 🙌🏻

**Pull request merged**
